// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyVienPhi.Models;

#nullable disable

namespace QuanLyVienPhi.Migrations
{
    [DbContext(typeof(QuanLyVienPhiContext))]
    [Migration("20250219120537_AddDaThanhToanToBenhNhan")]
    partial class AddDaThanhToanToBenhNhan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyVienPhi.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AdminId")
                        .HasName("PK__Admin__719FE4E8A5BFF347");

                    b.HasIndex(new[] { "Username" }, "UQ__Admin__536C85E4398DF850")
                        .IsUnique();

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.BacSi", b =>
                {
                    b.Property<int>("BacSiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BacSiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BacSiId"));

                    b.Property<string>("ChuyenKhoa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BacSiId")
                        .HasName("PK__BacSi__5B2D07542A824BF7");

                    b.ToTable("BacSi", (string)null);
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.BenhNhan", b =>
                {
                    b.Property<int>("BenhNhanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BenhNhanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenhNhanId"));

                    b.Property<int?>("BacSiId")
                        .HasColumnType("int")
                        .HasColumnName("BacSiID");

                    b.Property<string>("Cmnd")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("CMND");

                    b.Property<bool>("DaThanhToan")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("KhoaId")
                        .HasColumnType("int")
                        .HasColumnName("KhoaID");

                    b.Property<DateOnly>("NgayNhapVien")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayRaVien")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<int?>("PhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhongID");

                    b.Property<decimal?>("TienPhong")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TienThuoc")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("BenhNhanId")
                        .HasName("PK__BenhNhan__151050A6BBB20004");

                    b.HasIndex("BacSiId");

                    b.HasIndex("KhoaId");

                    b.HasIndex("PhongId");

                    b.ToTable("BenhNhan", (string)null);
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.ChiTietPhong", b =>
                {
                    b.Property<int>("ChiTietPhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChiTietPhongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietPhongId"));

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("int")
                        .HasColumnName("BenhNhanID");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int>("PhongId")
                        .HasColumnType("int")
                        .HasColumnName("PhongID");

                    b.Property<decimal>("TienPhong")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ChiTietPhongId")
                        .HasName("PK__ChiTietP__E1B170CDCFE9E1D9");

                    b.HasIndex("BenhNhanId");

                    b.HasIndex("PhongId");

                    b.ToTable("ChiTietPhong", (string)null);
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.ChiTietThuoc", b =>
                {
                    b.Property<int>("ChiTietThuocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChiTietThuocID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietThuocId"));

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("int")
                        .HasColumnName("BenhNhanID");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("ThuocId")
                        .HasColumnType("int")
                        .HasColumnName("ThuocID");

                    b.Property<decimal?>("TienThuoc")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ChiTietThuocId")
                        .HasName("PK__ChiTietT__E34DF085D9112CA1");

                    b.HasIndex("BenhNhanId");

                    b.HasIndex("ThuocId");

                    b.ToTable("ChiTietThuoc", (string)null);
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.HoaDon", b =>
                {
                    b.Property<int>("HoaDonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HoaDonID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonId"));

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("int")
                        .HasColumnName("BenhNhanID");

                    b.Property<decimal>("TienPhong")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TienThuoc")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(11, 2)")
                        .HasComputedColumnSql("([TienPhong]+[TienThuoc])", true);

                    b.HasKey("HoaDonId")
                        .HasName("PK__HoaDon__6956CE69F0192C85");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.Khoa", b =>
                {
                    b.Property<int>("KhoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KhoaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhoaId"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KhoaId")
                        .HasName("PK__Khoa__42EDDF14CB74A22A");

                    b.HasIndex(new[] { "TenKhoa" }, "UQ__Khoa__AAD3615830EED0CA")
                        .IsUnique();

                    b.ToTable("Khoa", (string)null);
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.Phong", b =>
                {
                    b.Property<int>("PhongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PhongID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhongId"));

                    b.Property<int>("KhoaId")
                        .HasColumnType("int")
                        .HasColumnName("KhoaID");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TienPhongNgay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PhongId")
                        .HasName("PK__Phong__FC669947BC716FF7");

                    b.HasIndex("KhoaId");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ThanhToanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanId"));

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("int")
                        .HasColumnName("HoaDonID");

                    b.Property<DateOnly>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ThuNganId")
                        .HasColumnType("int")
                        .HasColumnName("ThuNganID");

                    b.HasKey("ThanhToanId")
                        .HasName("PK__ThanhToa__24A8D684071FDBE2");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("ThuNganId");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.ThuNgan", b =>
                {
                    b.Property<int>("ThuNganId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ThuNganID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThuNganId"));

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ThuNganId")
                        .HasName("PK__ThuNgan__4CD824F59C05AF03");

                    b.ToTable("ThuNgan", (string)null);
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.Thuoc", b =>
                {
                    b.Property<int>("ThuocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ThuocID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThuocId"));

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ThuocId")
                        .HasName("PK__Thuoc__AB5C3E544F77143F");

                    b.ToTable("Thuoc", (string)null);
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.Ytum", b =>
                {
                    b.Property<int>("YtaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("YTaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YtaId"));

                    b.Property<string>("DienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("YtaId")
                        .HasName("PK__YTa__EF698884567CA9B2");

                    b.ToTable("YTa", (string)null);
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.BenhNhan", b =>
                {
                    b.HasOne("QuanLyVienPhi.Models.BacSi", "BacSi")
                        .WithMany("BenhNhans")
                        .HasForeignKey("BacSiId")
                        .HasConstraintName("FK__BenhNhan__BacSiI__45F365D3");

                    b.HasOne("QuanLyVienPhi.Models.Khoa", "Khoa")
                        .WithMany("BenhNhans")
                        .HasForeignKey("KhoaId")
                        .HasConstraintName("FK__BenhNhan__KhoaID__47DBAE45");

                    b.HasOne("QuanLyVienPhi.Models.Phong", "Phong")
                        .WithMany("BenhNhans")
                        .HasForeignKey("PhongId")
                        .HasConstraintName("FK__BenhNhan__PhongI__48CFD27E");

                    b.Navigation("BacSi");

                    b.Navigation("Khoa");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.ChiTietPhong", b =>
                {
                    b.HasOne("QuanLyVienPhi.Models.BenhNhan", "BenhNhan")
                        .WithMany("ChiTietPhongs")
                        .HasForeignKey("BenhNhanId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__BenhN__5165187F");

                    b.HasOne("QuanLyVienPhi.Models.Phong", "Phong")
                        .WithMany("ChiTietPhongs")
                        .HasForeignKey("PhongId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__Phong__52593CB8");

                    b.Navigation("BenhNhan");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.ChiTietThuoc", b =>
                {
                    b.HasOne("QuanLyVienPhi.Models.BenhNhan", "BenhNhan")
                        .WithMany("ChiTietThuocs")
                        .HasForeignKey("BenhNhanId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietTh__BenhN__4D94879B");

                    b.HasOne("QuanLyVienPhi.Models.Thuoc", "Thuoc")
                        .WithMany("ChiTietThuocs")
                        .HasForeignKey("ThuocId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietTh__Thuoc__4E88ABD4");

                    b.Navigation("BenhNhan");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.HoaDon", b =>
                {
                    b.HasOne("QuanLyVienPhi.Models.BenhNhan", "BenhNhan")
                        .WithMany("HoaDons")
                        .HasForeignKey("BenhNhanId")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDon__BenhNhan__5535A963");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.Phong", b =>
                {
                    b.HasOne("QuanLyVienPhi.Models.Khoa", "Khoa")
                        .WithMany("Phongs")
                        .HasForeignKey("KhoaId")
                        .IsRequired()
                        .HasConstraintName("FK_Phong_Khoa");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.ThanhToan", b =>
                {
                    b.HasOne("QuanLyVienPhi.Models.HoaDon", "HoaDon")
                        .WithMany("ThanhToans")
                        .HasForeignKey("HoaDonId")
                        .IsRequired()
                        .HasConstraintName("FK__ThanhToan__HoaDo__5812160E");

                    b.HasOne("QuanLyVienPhi.Models.ThuNgan", "ThuNgan")
                        .WithMany("ThanhToans")
                        .HasForeignKey("ThuNganId")
                        .IsRequired()
                        .HasConstraintName("FK__ThanhToan__ThuNg__6754599E");

                    b.Navigation("HoaDon");

                    b.Navigation("ThuNgan");
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.BacSi", b =>
                {
                    b.Navigation("BenhNhans");
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.BenhNhan", b =>
                {
                    b.Navigation("ChiTietPhongs");

                    b.Navigation("ChiTietThuocs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.HoaDon", b =>
                {
                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.Khoa", b =>
                {
                    b.Navigation("BenhNhans");

                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.Phong", b =>
                {
                    b.Navigation("BenhNhans");

                    b.Navigation("ChiTietPhongs");
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.ThuNgan", b =>
                {
                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("QuanLyVienPhi.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
